version: '3'
services:
  backend:
    container_name: wanna-bet
    build:
      context: .
      dockerfile: Dockerfile
    image: marquezin/wanna-bet-backend
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: wanna-bet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bernardo123
    ports:
      - "5432:5432"